import 'bootstrap/dist/css/bootstrap.min.css';
import {GlobalContextProvider} from  './context/context'
import{ ProductContextProvider }from './context/ProductContext'
import {CartContextProvider }from './context/CartContext'
import { config } from '@fortawesome/fontawesome-svg-core';
import { Cairo } from 'next/font/google';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import core styles

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";


config.autoAddCss = false; // Prevent duplicate loading in Next.js
const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({
  subsets: ['latin'], // Specify supported characters
 display: 'swap', // Preload font for faster rendering
});

export const metadata: Metadata = {
  title: "Hair Haven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartContextProvider>

    <GlobalContextProvider>
      <ProductContextProvider>

    
    <html lang="en">
      <body className={inter.className}>

              
             {children}
         
        </body>
    </html>
    </ProductContextProvider>
    </GlobalContextProvider>
    </CartContextProvider>
  );
}
