import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigation from '@/components/Navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full h-screen flex flex-row relative">
            <div className=" w-[7%] absolute top-0 left-0 h-full bg-white  shadow shadow-neutral-600">

          <Navigation />
            </div>
          <section className="flex absolute  flex-col  left-[7%] w-[93%] h-full gap-5">
                <div className="layout-container w-full h-full  bg-red-700 p-2 ">

                {children}
                </div>
          </section>
        </main>

      </body>
    </html>
  );
}
